version: '2.2'
services:
  # PHP-FPM Service
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/var/www/html
      - ../docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - database  
    networks:
      - my-network

  # NGINX Service
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - ../:/var/www/html 
    ports:
      - "8080:80"
    depends_on:
      - php-fpm 
      - database
    networks:
      - my-network

  # MySQL Database Service
  database:
    image: mysql:8.0
    env_file:
      - ../.env
    environment:
      MYSQL_ROOT_PASSWORD: ${password}
      MYSQL_DATABASE: ${db}
      MYSQL_USER: ${user}
      MYSQL_PASSWORD: ${password}
    volumes:
      - ./docker/database/unturned_shop.sql:/docker-entrypoint-initdb.d/unturned_shop.sql 
    ports:
      - "3307:3306"  
    networks:
      - my-network

  # PHPMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80" 
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: ${password}
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
